# Generated by Django 5.2.1 on 2025-05-13 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('HR', 'HR Собеседование'), ('HR_NO', 'Не прошел HR'), ('TECH', 'Тех. Собеседование'), ('TECH_NO', 'Не прошел тех.собес'), ('FINAL', 'На рассмотрении'), ('HIRED', 'Принят'), ('REJECTED', 'Отклонен')], default='HR', max_length=10, verbose_name='Статус')),
                ('hr_comment', models.TextField(blank=True, verbose_name='Комментарий HR')),
                ('tech_comment', models.TextField(blank=True, verbose_name='Комментарий тех.спеца')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
